---
title: "Project Phase 2" 
subtitle: "DS310"
author: "Arwa Hararwala, Krithika Senthil, & Swarali Korgaonkar"
output: html_notebook
---

Installing the libraries that are needed to be able to load and preform queries on the dataset.
```{r}
library(DataComputing)
library(tidyverse)
library(rvest)
library(lubridate)
library(dplyr)
library(readr)
library(ggplot2)
```


### Load Data
Getting the tables into RStudio to be able to use them for evaluation. We will do this using the read functions. 
```{r}
file_name <- file.choose()
sampleSubmission <- data.table::fread(file_name)
sampleSubmission
```

```{r}
file_name <- file.choose()
TrainData <- data.table::fread(file_name)
TrainData
```



```{r}
file_name <- file.choose()
TestData <- data.table::fread(file_name)
TestData
```


### Data Wrangling

```{r}

CleanedTrain <-
  TrainData %>%
  rename(RevenueGrowth = `Revenue Growth`) %>%
  rename(CostRevenue = `Cost of Revenue`) %>%
  rename(GrossProfit = `Gross Profit`) %>%
  rename(RDExpenses = `R&D Expenses`) %>%
  rename(SGAExpense= `SG&A Expense`) %>%
  rename(OpExpenses = `Operating Expenses`) %>%
  rename(OpIncome = `Operating Income`) %>%
  rename(InterestExpense = `Interest Expense`) %>%
  rename(IncomeTaxExpense = `Income Tax Expense`) %>%
  rename(NetIncome= `Net Income`) %>%
  rename(ProfitMargin = `Profit Margin`) %>%
  rename(NetProfitMargin= `Net Profit Margin`) %>%
  rename(TotalCurrentAssets = `Total current assets`) %>%
  rename(TotalAssets = `Total assets`) %>%
  rename(TotalDebt = `Total debt`) %>%
  rename(TaxLiability = `Tax Liabilities`) %>%
  rename(TotalNonCurrentAssests = `Net Debt`) %>%
  rename(InvestementPurchSales = `Investment purchases and sales`) %>%
  rename(AssetGrowth = `Asset Growth`) %>%
  rename(DebtGrowth = `Debt Growth`) 
CleanedTrain

```

```{r}
CleanedTest <-
  TestData %>%
  rename(RevenueGrowth = `Revenue Growth`) %>%
  rename(CostRevenue = `Cost of Revenue`) %>%
  rename(GrossProfit = `Gross Profit`) %>%
  rename(RDExpenses = `R&D Expenses`) %>%
  rename(SGAExpense= `SG&A Expense`) %>%
  rename(OpExpenses = `Operating Expenses`) %>%
  rename(OpIncome = `Operating Income`) %>%
  rename(InterestExpense = `Interest Expense`) %>%
  rename(IncomeTaxExpense = `Income Tax Expense`) %>%
  rename(NetIncome= `Net Income`) %>%
  rename(ProfitMargin = `Profit Margin`) %>%
  rename(NetProfitMargin= `Net Profit Margin`) %>%
  rename(TotalCurrentAssets = `Total current assets`) %>%
  rename(TotalAssets = `Total assets`) %>%
  rename(TotalDebt = `Total debt`) %>%
  rename(TaxLiability = `Tax Liabilities`) %>%
  rename(TotalNonCurrentAssests = `Net Debt`) %>%
  rename(InvestementPurchSales = `Investment purchases and sales`) %>%
  rename(AssetGrowth = `Asset Growth`) %>%
  rename(DebtGrowth = `Debt Growth`) 
CleanedTest
```

### Filter out the data to only have select variables for analysis
```{r}
NewTrain <-
  CleanedTrain %>%
  select(Name, netProfitMargin, Sector, RevenueGrowth, CostRevenue, GrossProfit, RDExpenses, SGAExpense, OpExpenses, OpIncome, InterestExpense, IncomeTaxExpense, NetIncome, ProfitMargin, NetProfitMargin, TotalCurrentAssets, TotalAssets, TotalDebt, TaxLiability, TotalNonCurrentAssests, InvestementPurchSales, AssetGrowth, DebtGrowth )

NewTrain
```

```{r}
NewTest <-
  CleanedTest%>%
  select(Name, netProfitMargin, Sector, RevenueGrowth, CostRevenue, GrossProfit, RDExpenses, SGAExpense, OpExpenses, OpIncome, InterestExpense, IncomeTaxExpense, NetIncome, ProfitMargin, NetProfitMargin, TotalCurrentAssets, TotalAssets, TotalDebt, TaxLiability, TotalNonCurrentAssests, InvestementPurchSales, AssetGrowth, DebtGrowth )

NewTest
```

